#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude -Ithirdparty
CFLAGS = -std=c++11 -Wextra -Wall -fPIC
RESINC = 
LIBDIR = 
LIB = thirdparty/curlcpp/build/libcurlcpp.a
LDFLAGS = -lssl -lcurl -lpugixml -ltidyp

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS)
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/libcdpp.so

INC_RELEASE = $(INC) -Iinclude -Iinclude/Container -Iinclude/hoster
CFLAGS_RELEASE = $(CFLAGS) -O2 -DBUILD_RELEASE
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/libcdpp.so

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/hoster/ZippyShareCom.o $(OBJDIR_DEBUG)/src/hoster/ShareOnlineBz.o $(OBJDIR_DEBUG)/src/container/RSDFParser.o $(OBJDIR_DEBUG)/src/container/Package.o $(OBJDIR_DEBUG)/src/container/DLCParser.o $(OBJDIR_DEBUG)/src/container/CCFParser.o $(OBJDIR_DEBUG)/src/basics/html.o $(OBJDIR_DEBUG)/src/basics/bio.o $(OBJDIR_DEBUG)/src/basics/aes.o $(OBJDIR_DEBUG)/src/basics/Logger.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/hoster/ZippyShareCom.o $(OBJDIR_RELEASE)/src/hoster/ShareOnlineBz.o $(OBJDIR_RELEASE)/src/container/RSDFParser.o $(OBJDIR_RELEASE)/src/container/Package.o $(OBJDIR_RELEASE)/src/container/DLCParser.o $(OBJDIR_RELEASE)/src/container/CCFParser.o $(OBJDIR_RELEASE)/src/basics/html.o $(OBJDIR_RELEASE)/src/basics/bio.o $(OBJDIR_RELEASE)/src/basics/aes.o $(OBJDIR_RELEASE)/src/basics/Logger.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src/hoster || mkdir -p $(OBJDIR_DEBUG)/src/hoster
	test -d $(OBJDIR_DEBUG)/src/container || mkdir -p $(OBJDIR_DEBUG)/src/container
	test -d $(OBJDIR_DEBUG)/src/basics || mkdir -p $(OBJDIR_DEBUG)/src/basics

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) -shared $(LIBDIR_DEBUG) $(OBJ_DEBUG)  -o $(OUT_DEBUG) $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/hoster/ZippyShareCom.o: src/hoster/ZippyShareCom.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/hoster/ZippyShareCom.cpp -o $(OBJDIR_DEBUG)/src/hoster/ZippyShareCom.o

$(OBJDIR_DEBUG)/src/hoster/ShareOnlineBz.o: src/hoster/ShareOnlineBz.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/hoster/ShareOnlineBz.cpp -o $(OBJDIR_DEBUG)/src/hoster/ShareOnlineBz.o

$(OBJDIR_DEBUG)/src/container/RSDFParser.o: src/container/RSDFParser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/container/RSDFParser.cpp -o $(OBJDIR_DEBUG)/src/container/RSDFParser.o

$(OBJDIR_DEBUG)/src/container/Package.o: src/container/Package.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/container/Package.cpp -o $(OBJDIR_DEBUG)/src/container/Package.o

$(OBJDIR_DEBUG)/src/container/DLCParser.o: src/container/DLCParser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/container/DLCParser.cpp -o $(OBJDIR_DEBUG)/src/container/DLCParser.o

$(OBJDIR_DEBUG)/src/container/CCFParser.o: src/container/CCFParser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/container/CCFParser.cpp -o $(OBJDIR_DEBUG)/src/container/CCFParser.o

$(OBJDIR_DEBUG)/src/basics/html.o: src/basics/html.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/basics/html.cpp -o $(OBJDIR_DEBUG)/src/basics/html.o

$(OBJDIR_DEBUG)/src/basics/bio.o: src/basics/bio.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/basics/bio.cpp -o $(OBJDIR_DEBUG)/src/basics/bio.o

$(OBJDIR_DEBUG)/src/basics/aes.o: src/basics/aes.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/basics/aes.cpp -o $(OBJDIR_DEBUG)/src/basics/aes.o

$(OBJDIR_DEBUG)/src/basics/Logger.o: src/basics/Logger.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/basics/Logger.cpp -o $(OBJDIR_DEBUG)/src/basics/Logger.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src/hoster
	rm -rf $(OBJDIR_DEBUG)/src/container
	rm -rf $(OBJDIR_DEBUG)/src/basics

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src/hoster || mkdir -p $(OBJDIR_RELEASE)/src/hoster
	test -d $(OBJDIR_RELEASE)/src/container || mkdir -p $(OBJDIR_RELEASE)/src/container
	test -d $(OBJDIR_RELEASE)/src/basics || mkdir -p $(OBJDIR_RELEASE)/src/basics

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) -shared $(LIBDIR_RELEASE) $(OBJ_RELEASE)  -o $(OUT_RELEASE) $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/hoster/ZippyShareCom.o: src/hoster/ZippyShareCom.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/hoster/ZippyShareCom.cpp -o $(OBJDIR_RELEASE)/src/hoster/ZippyShareCom.o

$(OBJDIR_RELEASE)/src/hoster/ShareOnlineBz.o: src/hoster/ShareOnlineBz.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/hoster/ShareOnlineBz.cpp -o $(OBJDIR_RELEASE)/src/hoster/ShareOnlineBz.o

$(OBJDIR_RELEASE)/src/container/RSDFParser.o: src/container/RSDFParser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/container/RSDFParser.cpp -o $(OBJDIR_RELEASE)/src/container/RSDFParser.o

$(OBJDIR_RELEASE)/src/container/Package.o: src/container/Package.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/container/Package.cpp -o $(OBJDIR_RELEASE)/src/container/Package.o

$(OBJDIR_RELEASE)/src/container/DLCParser.o: src/container/DLCParser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/container/DLCParser.cpp -o $(OBJDIR_RELEASE)/src/container/DLCParser.o

$(OBJDIR_RELEASE)/src/container/CCFParser.o: src/container/CCFParser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/container/CCFParser.cpp -o $(OBJDIR_RELEASE)/src/container/CCFParser.o

$(OBJDIR_RELEASE)/src/basics/html.o: src/basics/html.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/basics/html.cpp -o $(OBJDIR_RELEASE)/src/basics/html.o

$(OBJDIR_RELEASE)/src/basics/bio.o: src/basics/bio.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/basics/bio.cpp -o $(OBJDIR_RELEASE)/src/basics/bio.o

$(OBJDIR_RELEASE)/src/basics/aes.o: src/basics/aes.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/basics/aes.cpp -o $(OBJDIR_RELEASE)/src/basics/aes.o

$(OBJDIR_RELEASE)/src/basics/Logger.o: src/basics/Logger.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/basics/Logger.cpp -o $(OBJDIR_RELEASE)/src/basics/Logger.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src/hoster
	rm -rf $(OBJDIR_RELEASE)/src/container
	rm -rf $(OBJDIR_RELEASE)/src/basics

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

